language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_NDK_VERSION=r15c
  - ANDROID_NDK_HOME=/opt/android-ndk
  - ADB_INSTALL_TIMEOUT=20
  - CMAKE_VERSION=cmake-3.6.3
  - ANDROID_BUILD_TOOLS_VERSION=28.0.2
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
- sdkmanager tools
- sdkmanager "system-images;android-21;default;armeabi-v7a"
- rm -rf "$ANDROID_NDK_HOME"
- mkdir /opt/android-ndk-tmp
- cd /opt/android-ndk-tmp
- wget -q https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
  | cat
- unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip | cat
- mv ./android-ndk-${ANDROID_NDK_VERSION} ${ANDROID_NDK_HOME}
- cd ${ANDROID_NDK_HOME}
- rm -rf /opt/android-ndk-tmp
- cd ${TRAVIS_BUILD_DIR}
install:
- echo y | sdkmanager 'cmake;3.6.4111459' | grep -v "=$"
- echo y | sdkmanager 'lldb;3.0' | grep -v "=$"
before_script:
- export ANDROID_NDK_HOME=$ANDROID_NDK_HOME
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-15
  - android-25
  - android-21
  - android-28
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-+
  - android-sdk-license-.+
  - google-gdk-license-.+
notifications:
  email: false
script:
#- "./gradlew test"
- "./gradlew assemble_testNet3Debug"
#- rm -rf .gradle/4.4
#- "./gradlew assembleProdDebug"
#- "./gradlew assembleProdRelease"
deploy:
  provider: releases
  api_key: d42b4e7f8b041fc604daeff4e744c5e2a0f9bb4d
  file: wallet/build/outputs/apk/_testNet3/debug/wallet*release*.apk
  on:
    repo: dashevo/dash-wallet
    branch: develop
  skip_cleanup: 'true'
